### ISSUE TITLE
bypass still uses same amount of CPU

### ISSUE THREAD

**Issue by kjyv** [moddevices/mod-host#23]
This is maybe half a feature request, half a question. I understand the bypass command is intended to temporarily disable effects in the processing chain. I've noticed that plugins which are bypassed still run as if they were not bypassed, no input and no output is passed. Would it be possible within mod-host/lilv to set these plugins to a proper idle mode so they consume no cpu?

**Comment by falkTX** [comment]
Sorry for the super long time in replying here.
But the answer if that, intentionally, mod-host keeps plugins running while they are bypassed (just with zero input buffers).
The idea is to keep plugins that use time always in sync, as otherwise we would have phase issues.

The CPU load depends on the plugin, some plugins do nothing when their input is zero, but some dont.
In any case, it is working as intended.
